export interface TileOption {
  id: string;
  name: string;
  category: string;
  colorHex: string;
  prompt: string;
  thumbnailUrl: string;
}

export const TILE_CATALOG: TileOption[] = [
  // --- Architectural Tiles ---
  {
    id: 'arch-terracotta',
    name: 'Terracotta Red',
    category: 'Architectural Tiles',
    colorHex: '#8b3a2b',
    prompt: 'red terracotta spanish roof tiles',
    thumbnailUrl: '/architectural/terracotta_red.png',
  },
  {
    id: 'arch-slate',
    name: 'Slate Grey',
    category: 'Architectural Tiles',
    colorHex: '#4a5568',
    prompt: 'dark grey slate roof tiles',
    thumbnailUrl: '/architectural/slate_grey.png',
  },
  {
    id: 'arch-clay',
    name: 'Mediterranean Clay',
    category: 'Architectural Tiles',
    colorHex: '#cd5c5c',
    prompt: 'mediterranean clay barrel roof tiles',
    thumbnailUrl: '/architectural/mediterranean_clay.png',
  },
  {
    id: 'arch-metal',
    name: 'Forest Green Metal',
    category: 'Architectural Tiles',
    colorHex: '#2f4f4f',
    prompt: 'forest green metal standing seam roof',
    thumbnailUrl: '/architectural/forest_green_metal.png',
  },
  {
    id: 'arch-wood',
    name: 'Weathered Wood Cedar',
    category: 'Architectural Tiles',
    colorHex: '#8b7355',
    prompt: 'weathered wood cedar shake roof',
    thumbnailUrl: '/architectural/cedar_shake.png',
  },

  // --- GAF Timberline HDZ Asphalt Shingles ---
  {
    id: 'gaf-barkwood',
    name: 'Barkwood',
    category: 'GAF Timberline HDZ',
    colorHex: '#5c4a3c',
    prompt: 'dark brown asphalt shingle roof, textured dark bark brown shingles, GAF Timberline barkwood color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Barkwood.avif',
  },
  {
    id: 'gaf-birchwood',
    name: 'Birchwood',
    category: 'GAF Timberline HDZ',
    colorHex: '#bfae9e',
    prompt: 'light silver grey asphalt shingle roof, pale warm grey shingles, soft taupe grey roof tiles, GAF Timberline birchwood color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Birchwood.avif',
  },
  {
    id: 'gaf-biscayne-blue',
    name: 'Biscayne Blue',
    category: 'GAF Timberline HDZ',
    colorHex: '#3b5a75',
    prompt: 'slate blue asphalt shingle roof, deep navy blue grey shingles, steel blue roof tiles, GAF Timberline biscayne blue color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Biscayne Blue.avif',
  },
  {
    id: 'gaf-chestnut-valley',
    name: 'Chestnut Valley',
    category: 'GAF Timberline HDZ',
    colorHex: '#4a3b2c',
    prompt: 'deep dark chestnut brown asphalt shingle roof, rich warm brown shingles, dark brown roof tiles, GAF Timberline chestnut valley color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Chestnut Valley.avif',
  },
  {
    id: 'gaf-cliffside',
    name: 'Cliffside',
    category: 'GAF Timberline HDZ',
    colorHex: '#6b7075',
    prompt: 'medium stone grey asphalt shingle roof, cool neutral grey shingles, textured grey roof tiles, GAF Timberline cliffside color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Cliffside.avif',
  },
  {
    id: 'gaf-copper-canyon',
    name: 'Copper Canyon',
    category: 'GAF Timberline HDZ',
    colorHex: '#804a30',
    prompt: 'reddish brown asphalt shingle roof, warm copper terracotta brown shingles, burnt sienna roof tiles, GAF Timberline copper canyon color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Copper Canyon.avif',
  },
  {
    id: 'gaf-driftwood',
    name: 'Driftwood',
    category: 'GAF Timberline HDZ',
    colorHex: '#7c7267',
    prompt: 'greyed brown asphalt shingle roof, warm taupe grey-brown shingles, weathered muted brown roof tiles, GAF Timberline driftwood color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Driftwood.avif',
  },
  {
    id: 'gaf-fox-hollow',
    name: 'Fox Hollow',
    category: 'GAF Timberline HDZ',
    colorHex: '#8c9094',
    prompt: 'pale light grey asphalt shingle roof, soft cool grey shingles, light pewter grey roof tiles, GAF Timberline fox hollow color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Fox Hollow.avif',
  },
  {
    id: 'gaf-golden-amber',
    name: 'Golden Amber',
    category: 'GAF Timberline HDZ',
    colorHex: '#a67438',
    prompt: 'warm golden brown asphalt shingle roof, honey amber colored shingles, rich ochre gold brown roof tiles, GAF Timberline golden amber color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Golden Amber.avif',
  },
  {
    id: 'gaf-hickory',
    name: 'Hickory',
    category: 'GAF Timberline HDZ',
    colorHex: '#3b2d21',
    prompt: 'very dark brown asphalt shingle roof, deep espresso brown shingles, near-black dark brown roof tiles, GAF Timberline hickory color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Hickory.avif',
  },
  {
    id: 'gaf-hunter-green',
    name: 'Hunter Green',
    category: 'GAF Timberline HDZ',
    colorHex: '#26402d',
    prompt: 'dark forest green asphalt shingle roof, deep hunter green shingles, dark emerald green roof tiles, GAF Timberline hunter green color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Hunter Green.avif',
  },
  {
    id: 'gaf-midnight-mesa',
    name: 'Midnight Mesa',
    category: 'GAF Timberline HDZ',
    colorHex: '#2c2826',
    prompt: 'near-black charcoal brown asphalt shingle roof, very dark warm grey-brown shingles, dark charcoal roof tiles, GAF Timberline midnight mesa color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Midnight Mesa.avif',
  },
  {
    id: 'gaf-mission-brown',
    name: 'Mission Brown',
    category: 'GAF Timberline HDZ',
    colorHex: '#403024',
    prompt: 'dark soil brown asphalt shingle roof, warm deep brown shingles, rich dark umber brown roof tiles, GAF Timberline mission brown color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Mission Brown.avif',
  },
  {
    id: 'gaf-oyster-gray',
    name: 'Oyster Gray',
    category: 'GAF Timberline HDZ',
    colorHex: '#a8aba6',
    prompt: 'pale light grey asphalt shingle roof, soft warm grey shingles, oyster white-grey roof tiles, GAF Timberline oyster gray color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Oyster Gray.avif',
  },
  {
    id: 'gaf-patriot-red',
    name: 'Patriot Red',
    category: 'GAF Timberline HDZ',
    colorHex: '#7a2b2d',
    prompt: 'deep brick red asphalt shingle roof, dark crimson red shingles, rich dark wine red roof tiles, GAF Timberline patriot red color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Patriot Red.avif',
  },
  {
    id: 'gaf-pewter-gray',
    name: 'Pewter Gray',
    category: 'GAF Timberline HDZ',
    colorHex: '#575a5e',
    prompt: 'dark charcoal grey asphalt shingle roof, deep pewter grey shingles, medium dark grey roof tiles, GAF Timberline pewter gray color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Pewter Gray.avif',
  },
  {
    id: 'gaf-shakewood',
    name: 'Shakewood',
    category: 'GAF Timberline HDZ',
    colorHex: '#9e8e78',
    prompt: 'light sandy wood brown asphalt shingle roof, warm tan-brown shingles, medium beige brown roof tiles, GAF Timberline shakewood color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Shakewood.avif',
  },
  {
    id: 'gaf-sierra-sand',
    name: 'Sierra Sand',
    category: 'GAF Timberline HDZ',
    colorHex: '#aba291',
    prompt: 'sandy beige asphalt shingle roof, warm sand tan shingles, light desert tan roof tiles, GAF Timberline sierra sand color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Sierra Sand.avif',
  },
  {
    id: 'gaf-sunset-brick',
    name: 'Sunset Brick',
    category: 'GAF Timberline HDZ',
    colorHex: '#944b36',
    prompt: 'warm terracotta brick red asphalt shingle roof, reddish orange-brown shingles, clay brick red roof tiles, GAF Timberline sunset brick color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Sunset Brick.avif',
  },
  {
    id: 'gaf-weathered-wood',
    name: 'Weathered Wood',
    category: 'GAF Timberline HDZ',
    colorHex: '#6b5d52',
    prompt: 'rustic brown asphalt shingle roof, weathered medium brown shingles, warm grey-brown aged wood roof tiles, GAF Timberline weathered wood color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Weathered Wood.avif',
  },
  {
    id: 'gaf-williamsburg-slate',
    name: 'Williamsburg Slate',
    category: 'GAF Timberline HDZ',
    colorHex: '#48525c',
    prompt: 'blue-grey slate asphalt shingle roof, cool grey-blue shingles, slate blue charcoal roof tiles, GAF Timberline williamsburg slate color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Williamsburg Slate.avif',
  },

  // --- Owens Corning Supreme Asphalt Shingles ---
  {
    id: 'oc-autumn-brown',
    name: 'Autumn Brown',
    category: 'Owens Corning Supreme',
    colorHex: '#5c4333',
    prompt: 'warm medium brown asphalt shingle roof, rich autumn brown shingles, earthy warm brown roof tiles, Owens Corning autumn brown color',
    thumbnailUrl: '/shingles/Owens Corning Supreme Autumn Brown.avif',
  },
  {
    id: 'oc-brownwood',
    name: 'Brownwood',
    category: 'Owens Corning Supreme',
    colorHex: '#4a382c',
    prompt: 'deep dark brown asphalt shingle roof, rich dark chocolate brown shingles, dark wood brown roof tiles, Owens Corning brownwood color',
    thumbnailUrl: '/shingles/Owens Corning Supreme Brownwood.avif',
  },
  {
    id: 'oc-desert-tan',
    name: 'Desert Tan',
    category: 'Owens Corning Supreme',
    colorHex: '#a39178',
    prompt: 'sandy tan beige asphalt shingle roof, warm light tan shingles, desert sand beige roof tiles, Owens Corning desert tan color',
    thumbnailUrl: '/shingles/Owens Corning Supreme Desert Tan.avif',
  },
  {
    id: 'oc-driftwood',
    name: 'Driftwood',
    category: 'Owens Corning Supreme',
    colorHex: '#6e665a',
    prompt: 'warm grey-brown asphalt shingle roof, muted taupe brown shingles, weathered medium grey-brown roof tiles, Owens Corning driftwood color',
    thumbnailUrl: '/shingles/Owens Corning Supreme Driftwood.avif',
  },
  {
    id: 'oc-estate-gray',
    name: 'Estate Gray',
    category: 'Owens Corning Supreme',
    colorHex: '#5d6166',
    prompt: 'medium charcoal grey asphalt shingle roof, cool dark grey shingles, slate grey roof tiles, Owens Corning estate gray color',
    thumbnailUrl: '/shingles/Owens Corning Supreme Estate Gray.avif',
  },
  {
    id: 'oc-onyx-black',
    name: 'Onyx Black',
    category: 'Owens Corning Supreme',
    colorHex: '#1f2021',
    prompt: 'near-black charcoal asphalt shingle roof, very dark black shingles, jet black roof tiles, Owens Corning onyx black color',
    thumbnailUrl: '/shingles/Owens Corning Supreme Onyx Black.avif',
  },
  {
    id: 'oc-shasta-white',
    name: 'Shasta White',
    category: 'Owens Corning Supreme',
    colorHex: '#e3e5e6',
    prompt: 'bright clean white asphalt shingle roof, light white-grey shingles, pale off-white roof tiles with light grey shadows, Owens Corning shasta white color',
    thumbnailUrl: '/shingles/Owens Corning Supreme Shasta White.avif',
  },
  {
    id: 'oc-teak',
    name: 'Teak',
    category: 'Owens Corning Supreme',
    colorHex: '#453526',
    prompt: 'dark teak brown asphalt shingle roof, deep warm dark brown shingles, rich espresso brown roof tiles, Owens Corning teak color',
    thumbnailUrl: '/shingles/Owens Corning Supreme Teak.avif',
  },
];
