export interface TileOption {
  id: string;
  name: string;
  category: string;
  colorHex: string;
  prompt: string;
  thumbnailUrl: string;
}

export const TILE_CATALOG: TileOption[] = [
  // --- Architectural Tiles ---
  {
    id: 'arch-terracotta',
    name: 'Terracotta Red',
    category: 'Architectural Tiles',
    colorHex: '#8b3a2b',
    prompt: 'red terracotta spanish roof tiles',
    thumbnailUrl: '/architectural/terracotta_red.png',
  },
  {
    id: 'arch-slate',
    name: 'Slate Grey',
    category: 'Architectural Tiles',
    colorHex: '#4a5568',
    prompt: 'dark grey slate roof tiles',
    thumbnailUrl: '/architectural/slate_grey.png',
  },
  {
    id: 'arch-clay',
    name: 'Mediterranean Clay',
    category: 'Architectural Tiles',
    colorHex: '#cd5c5c',
    prompt: 'mediterranean clay barrel roof tiles',
    thumbnailUrl: '/architectural/mediterranean_clay.png',
  },
  {
    id: 'arch-metal',
    name: 'Forest Green Metal',
    category: 'Architectural Tiles',
    colorHex: '#2f4f4f',
    prompt: 'forest green metal standing seam roof',
    thumbnailUrl: '/architectural/forest_green_metal.png',
  },
  {
    id: 'arch-wood',
    name: 'Weathered Wood Cedar',
    category: 'Architectural Tiles',
    colorHex: '#8b7355',
    prompt: 'weathered wood cedar shake roof',
    thumbnailUrl: '/architectural/cedar_shake.png',
  },

  // --- GAF Timberline HDZ Asphalt Shingles ---
  {
    id: 'gaf-barkwood',
    name: 'Barkwood',
    category: 'GAF Timberline HDZ',
    colorHex: '#5c4a3c',
    prompt: 'barkwood, dark brown asphalt shingles roof, textured brown shingles',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Barkwood.avif',
  },
  {
    id: 'gaf-birchwood',
    name: 'Birchwood',
    category: 'GAF Timberline HDZ',
    colorHex: '#bfae9e',
    prompt: 'birchwood, light grey asphalt shingles roof, silver grey shingles',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Birchwood.avif',
  },
  {
    id: 'gaf-biscayne-blue',
    name: 'Biscayne Blue',
    category: 'GAF Timberline HDZ',
    colorHex: '#3b5a75',
    prompt: 'biscayne blue, slate blue asphalt shingles roof, navy blue color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Biscayne Blue.avif',
  },
  {
    id: 'gaf-chestnut-valley',
    name: 'Chestnut Valley',
    category: 'GAF Timberline HDZ',
    colorHex: '#4a3b2c',
    prompt: 'chestnut valley, deep brown asphalt shingles roof, dark chestnut brown',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Chestnut Valley.avif',
  },
  {
    id: 'gaf-cliffside',
    name: 'Cliffside',
    category: 'GAF Timberline HDZ',
    colorHex: '#6b7075',
    prompt: 'cliffside grey, medium grey asphalt shingles roof, stone grey',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Cliffside.avif',
  },
  {
    id: 'gaf-copper-canyon',
    name: 'Copper Canyon',
    category: 'GAF Timberline HDZ',
    colorHex: '#804a30',
    prompt: 'copper canyon, reddish brown asphalt shingles roof, warm copper terracotta brown',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Copper Canyon.avif',
  },
  {
    id: 'gaf-driftwood',
    name: 'Driftwood',
    category: 'GAF Timberline HDZ',
    colorHex: '#7c7267',
    prompt: 'driftwood, greyish brown asphalt shingles roof, weathered driftwood color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Driftwood.avif',
  },
  {
    id: 'gaf-fox-hollow',
    name: 'Fox Hollow',
    category: 'GAF Timberline HDZ',
    colorHex: '#8c9094',
    prompt: 'fox hollow, light grey asphalt shingles roof, pale grey shingles',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Fox Hollow.avif',
  },
  {
    id: 'gaf-golden-amber',
    name: 'Golden Amber',
    category: 'GAF Timberline HDZ',
    colorHex: '#a67438',
    prompt: 'golden amber, warm golden brown asphalt shingles roof, amber honey color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Golden Amber.avif',
  },
  {
    id: 'gaf-hickory',
    name: 'Hickory',
    category: 'GAF Timberline HDZ',
    colorHex: '#3b2d21',
    prompt: 'hickory, dark brown asphalt shingles roof, deep hickory brown',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Hickory.avif',
  },
  {
    id: 'gaf-hunter-green',
    name: 'Hunter Green',
    category: 'GAF Timberline HDZ',
    colorHex: '#26402d',
    prompt: 'hunter green, dark forest green asphalt shingles roof, deep green color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Hunter Green.avif',
  },
  {
    id: 'gaf-midnight-mesa',
    name: 'Midnight Mesa',
    category: 'GAF Timberline HDZ',
    colorHex: '#2c2826',
    prompt: 'midnight mesa, dark brown asphalt shingles roof, near-black charcoal brown',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Midnight Mesa.avif',
  },
  {
    id: 'gaf-mission-brown',
    name: 'Mission Brown',
    category: 'GAF Timberline HDZ',
    colorHex: '#403024',
    prompt: 'mission brown, dark soil brown asphalt shingles roof, warm brown',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Mission Brown.avif',
  },
  {
    id: 'gaf-oyster-gray',
    name: 'Oyster Gray',
    category: 'GAF Timberline HDZ',
    colorHex: '#a8aba6',
    prompt: 'oyster gray, light grey asphalt shingles roof, pale oyster grey',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Oyster Gray.avif',
  },
  {
    id: 'gaf-patriot-red',
    name: 'Patriot Red',
    category: 'GAF Timberline HDZ',
    colorHex: '#7a2b2d',
    prompt: 'patriot red, deep brick red asphalt shingles roof, dark red color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Patriot Red.avif',
  },
  {
    id: 'gaf-pewter-gray',
    name: 'Pewter Gray',
    category: 'GAF Timberline HDZ',
    colorHex: '#575a5e',
    prompt: 'pewter gray, dark grey asphalt shingles roof, charcoal pewter grey',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Pewter Gray.avif',
  },
  {
    id: 'gaf-shakewood',
    name: 'Shakewood',
    category: 'GAF Timberline HDZ',
    colorHex: '#9e8e78',
    prompt: 'shakewood, light brown asphalt shingles roof, sandy wood brown',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Shakewood.avif',
  },
  {
    id: 'gaf-sierra-sand',
    name: 'Sierra Sand',
    category: 'GAF Timberline HDZ',
    colorHex: '#aba291',
    prompt: 'sierra sand, beige asphalt shingles roof, sandy tan color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Sierra Sand.avif',
  },
  {
    id: 'gaf-sunset-brick',
    name: 'Sunset Brick',
    category: 'GAF Timberline HDZ',
    colorHex: '#944b36',
    prompt: 'sunset brick, reddish terracotta asphalt shingles roof, warm brick red',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Sunset Brick.avif',
  },
  {
    id: 'gaf-weathered-wood',
    name: 'Weathered Wood',
    category: 'GAF Timberline HDZ',
    colorHex: '#6b5d52',
    prompt: 'weathered wood, brown asphalt shingles roof, rustic weathered wood color',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Weathered Wood.avif',
  },
  {
    id: 'gaf-williamsburg-slate',
    name: 'Williamsburg Slate',
    category: 'GAF Timberline HDZ',
    colorHex: '#48525c',
    prompt: 'williamsburg slate, blue-grey asphalt shingles roof, slate blue',
    thumbnailUrl: '/shingles/GAF Timberline HDZ Williamsburg Slate.avif',
  },

  // --- Owens Corning Supreme Asphalt Shingles ---
  {
    id: 'oc-autumn-brown',
    name: 'Autumn Brown',
    category: 'Owens Corning Supreme',
    colorHex: '#5c4333',
    prompt: 'autumn brown, warm brown asphalt shingles roof, autumn foliage brown',
    thumbnailUrl: '/shingles/Owens Corning Supreme Autumn Brown.avif',
  },
  {
    id: 'oc-brownwood',
    name: 'Brownwood',
    category: 'Owens Corning Supreme',
    colorHex: '#4a382c',
    prompt: 'brownwood, dark brown asphalt shingles roof, wood brown',
    thumbnailUrl: '/shingles/Owens Corning Supreme Brownwood.avif',
  },
  {
    id: 'oc-desert-tan',
    name: 'Desert Tan',
    category: 'Owens Corning Supreme',
    colorHex: '#a39178',
    prompt: 'desert tan, sandy beige asphalt shingles roof, tan color',
    thumbnailUrl: '/shingles/Owens Corning Supreme Desert Tan.avif',
  },
  {
    id: 'oc-driftwood',
    name: 'Driftwood',
    category: 'Owens Corning Supreme',
    colorHex: '#6e665a',
    prompt: 'driftwood, greyish brown asphalt shingles roof, weathered wood',
    thumbnailUrl: '/shingles/Owens Corning Supreme Driftwood.avif',
  },
  {
    id: 'oc-estate-gray',
    name: 'Estate Gray',
    category: 'Owens Corning Supreme',
    colorHex: '#5d6166',
    prompt: 'estate gray, medium grey asphalt shingles roof, slate grey',
    thumbnailUrl: '/shingles/Owens Corning Supreme Estate Gray.avif',
  },
  {
    id: 'oc-onyx-black',
    name: 'Onyx Black',
    category: 'Owens Corning Supreme',
    colorHex: '#1f2021',
    prompt: 'onyx black, deep dark black asphalt shingles roof, charcoal black',
    thumbnailUrl: '/shingles/Owens Corning Supreme Onyx Black.avif',
  },
  {
    id: 'oc-shasta-white',
    name: 'Shasta White',
    category: 'Owens Corning Supreme',
    colorHex: '#e3e5e6',
    prompt: 'shasta white, bright clean white asphalt shingles roof, light grey shadows, white color',
    thumbnailUrl: '/shingles/Owens Corning Supreme Shasta White.avif',
  },
  {
    id: 'oc-teak',
    name: 'Teak',
    category: 'Owens Corning Supreme',
    colorHex: '#453526',
    prompt: 'teak, dark teak brown asphalt shingles roof, deep brown',
    thumbnailUrl: '/shingles/Owens Corning Supreme Teak.avif',
  },
];
